version: "3.8"

services:
  database:
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    environment:
       ADMINER_DESIGN: pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      - database