version: "3.8"

services:

  traefik:
    image: traefik:v2.7
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80

      # https
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=$TRAEFIK_LE_EMAIL
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true

      - --accesslog
      - --log

      # traefik dashboard
      - --api

    labels:
      # traefik dashboard
      - traefik.enable=true
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik.milf-tochka.ru`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.traefik-dashboard-https.entrypoints=https
      - traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik.milf-tochka.ru`)
      - traefik.http.routers.traefik-dashboard-https.tls=true
      - traefik.http.routers.traefik-dashboard-https.tls.certresolver=le
      - traefik.http.routers.traefik-dashboard-https.service=api@internal
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect

      # traefik dashboard auth
      - traefik.http.middlewares.admin-auth.basicauth.users=${TRAEFIK_USERNAME?Traefik variable USERNAME not set}:${TRAEFIK_HASHED_PASSWORD?Traefik variable HASHED_PASSWORD not set}
      - traefik.http.routers.traefik-dashboard-https.middlewares=admin-auth

    networks:
      - traefik-public


volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    external: true
