version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    environment:
       ADMINER_DESIGN: pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      - database
